// ============================================================================
// LaTeX (.tex) export.
//
// Aimed at someone who wants to keep editing the CV in LaTeX, so the output is
// meant to be read and changed by hand: no exotic packages, one macro per block
// type at the top, and the content below in plain, obvious commands.
//
// Geometry and typography come from the same two modules the preview uses
// (`cvDocModel` for content and order, `cvTypography` for sizes and rules), so a
// compiled .tex lands on the same page shape as the PDF: A4, 0.75in margins,
// the same point sizes, the same accent colour.
//
// Compiler: pdflatex for an English CV; an Arabic CV needs xelatex (or
// lualatex) because Arabic shaping requires a Unicode engine. The generated file
// says so in its own header comment and loads the right packages either way.
// ============================================================================

import { buildCvModel } from "@/lib/cvDocModel";
import { COLORS, pxToPt } from "@/lib/cvTypography";
import { PAGE_MARGIN_IN } from "@/lib/cvTemplateMeta";

// LaTeX font packages that match each template's face. Chosen for metric or
// visual closeness to the web font, and all present in a standard TeX Live.
const FONT_PACKAGES = {
  Arial: { pkg: "helvet", sans: true, note: "Helvetica — the TeX metric match for Arial" },
  Calibri: { pkg: "carlito", sans: true, note: "Carlito — metric-compatible with Calibri" },
  Georgia: { pkg: "tgpagella", sans: false, note: "TeX Gyre Pagella — a Georgia-like serif" },
  Garamond: { pkg: "ebgaramond", sans: false, note: "EB Garamond" },
};

// Characters LaTeX treats as syntax. Applied in one pass: replacing them one
// rule at a time would re-escape the braces that the earlier replacements
// introduce, turning a single backslash into `\textbackslash\{\}`.
const ESCAPES = {
  "\\": "\\textbackslash{}",
  "&": "\\&",
  "%": "\\%",
  $: "\\$",
  "#": "\\#",
  _: "\\_",
  "{": "\\{",
  "}": "\\}",
  "~": "\\textasciitilde{}",
  "^": "\\textasciicircum{}",
};

// Escapes a user string for LaTeX, keeping their line breaks: a single newline
// becomes an explicit `\\` break, a blank line becomes a real paragraph break.
// (The block macros are defined with \newcommand, which is \long, so a
// paragraph break inside a macro argument is legal.)
export function tex(value) {
  const escaped = String(value ?? "").replace(/[\\&%$#_{}~^]/g, (ch) => ESCAPES[ch]);
  return escaped
    .split(/\n{2,}/)
    .map((para) => para.split("\n").map((line) => line.trimEnd()).join("\\\\\n"))
    .filter(Boolean)
    .join("\n\n");
}

// Colour for \definecolor{...}{HTML}{...} — uppercase, no leading hash.
const hexColor = (color) => String(color || "#000000").replace("#", "").toUpperCase();

// `\fontsize{size}{leading}\selectfont`, both in points. The trailing empty
// group stops \selectfont from swallowing the space before the text that
// follows it — and from running into that text as one long control word.
function fontSize(sizePt, lineHeight) {
  return `\\fontsize{${round(sizePt)}pt}{${round(sizePt * lineHeight)}pt}\\selectfont{}`;
}

// Same, but with the leading given directly in points — used where two boxes
// must share a first-line height so their baselines line up.
function fontSizeRaw(sizePt, leadingPt) {
  return `\\fontsize{${round(sizePt)}pt}{${round(leadingPt)}pt}\\selectfont{}`;
}

function round(n) {
  return Math.round(Number(n) * 100) / 100;
}

// --- Preamble ----------------------------------------------------------------

function preamble(model) {
  const { typo } = model;
  const font = FONT_PACKAGES[model.font] || FONT_PACKAGES.Arial;
  const engine = model.rtl ? "xelatex" : "pdflatex";

  const fontSetup = model.rtl
    ? `% Arabic needs a Unicode engine and a font with Arabic coverage.
\\usepackage{fontspec}
\\usepackage{polyglossia}
\\setmainlanguage{arabic}
\\setotherlanguage{english}
% Cairo is the face the website uses. Any installed Arabic font works here.
\\newfontfamily\\arabicfont[Script=Arabic]{Cairo}`
    : `% ${font.note}
\\usepackage[T1]{fontenc}
\\usepackage[utf8]{inputenc}
\\usepackage{${font.pkg}}
${font.sans ? "\\renewcommand{\\familydefault}{\\sfdefault}" : ""}`;

  return `% =============================================================================
% ${tex(model.documentTitle)} — CV
% Generated by Bornat CV Maker (template: ${model.template.name}).
%
% Compile with: ${engine} cv.tex
%
% Everything below is plain LaTeX — edit it freely. The macros in the "Building
% blocks" section define how each part of the CV is set; change one of those to
% restyle every block of that kind at once.
% =============================================================================
\\documentclass[a4paper]{article}

\\usepackage[margin=${PAGE_MARGIN_IN}in]{geometry}
${fontSetup}
\\usepackage{xcolor}
\\usepackage{enumitem}
\\usepackage{anyfontsize}
\\usepackage{needspace}
\\usepackage[hidelinks]{hyperref}

\\definecolor{accent}{HTML}{${hexColor(model.accent)}}
\\definecolor{bodytext}{HTML}{${hexColor(COLORS.body)}}
\\definecolor{subtext}{HTML}{${hexColor(COLORS.itemSub)}}
\\definecolor{datetext}{HTML}{${hexColor(COLORS.itemDate)}}
\\definecolor{contacttext}{HTML}{${hexColor(COLORS.contact)}}
\\definecolor{rulegrey}{HTML}{${hexColor(typo.sectionRuleColor === "accent" ? model.accent : typo.sectionRuleColor || "#D4D4D4")}}
\\definecolor{sepgrey}{HTML}{${hexColor(COLORS.inlineSeparator)}}
\\definecolor{septext}{HTML}{${hexColor(COLORS.separator)}}

\\pagestyle{empty}
\\setlength{\\parindent}{0pt}
\\color{bodytext}
${fontSize(typo.body, typo.lineHeight)}

% --- Building blocks ---------------------------------------------------------

% Name and the line under it.
\\newcommand{\\cvname}[1]{{\\color{accent}\\bfseries ${fontSize(typo.name, 1.15)} #1\\par}}
\\newcommand{\\cvjobtitle}[1]{{${jobTitleSetup(model)} #1\\par}}
\\newcommand{\\cvcontact}[1]{{\\color{contacttext}${fontSize(typo.contact, 1.35)} #1\\par}}
\\newcommand{\\cvsep}{{\\color{septext}\\hspace{4pt}|\\hspace{4pt}}}

% A section heading, with the rule the template draws under it. The optional
% argument is the space above it, so the first section can sit tighter to the
% header than the ones that follow.
\\newcommand{\\cvsection}[2][${pxToPt(typo.space.sectionGap)}pt]{%
  \\needspace{3\\baselineskip}%
  \\vspace{#1}%
  {\\color{accent}\\bfseries\\MakeUppercase{${fontSize(typo.sectionTitle, 1.2)} #2}\\par}%
  ${
    typo.sectionRulePx > 0
      ? `\\vspace{${pxToPt(typo.space.sectionTitlePad)}pt}{\\color{rulegrey}\\hrule height ${pxToPt(typo.sectionRulePx)}pt}`
      : ""
  }%
  \\vspace{${pxToPt(typo.space.sectionTitleGap)}pt}%
}

% A dated entry: bold title on one side, date on the other. Two top-aligned
% boxes rather than an \\hfill, so that a title running onto a second line keeps
% the date up on the first — which is where the web version puts it.
\\newcommand{\\cventry}[3][${pxToPt(typo.space.itemGap)}pt]{%
  \\vspace{#1}%
  \\noindent\\begin{minipage}[t]{0.72\\linewidth}\\raggedright%
    ${fontSize(typo.itemTitle, typo.lineHeight)}\\strut{\\bfseries #2}%
  \\end{minipage}\\hfill\\begin{minipage}[t]{0.26\\linewidth}\\raggedleft%
    % The strut is set at the title's size in both boxes, so both first lines are
    % the same height and the two [t]-aligned boxes share a baseline.
    ${fontSize(typo.itemTitle, typo.lineHeight)}\\strut{\\color{datetext}${
      typo.itemDateItalic ? "\\itshape" : ""
    }${fontSizeRaw(typo.itemDate, typo.itemTitle * typo.lineHeight)} #3}%
  \\end{minipage}\\par%
}
\\newcommand{\\cvsubtitle}[1]{{\\color{subtext}${typo.itemSubItalic ? "\\itshape" : ""} #1\\par}}
\\newcommand{\\cvdetail}[1]{\\vspace{${pxToPt(typo.space.detailTop)}pt}{\\color{subtext} #1\\par}}

% Bullet lists, set with the same indent and accent bullet as the web version.
\\newlist{cvbullets}{itemize}{1}
\\setlist[cvbullets]{
  label={\\color{accent}\\textbullet},
  leftmargin=${pxToPt(13)}pt, labelsep=4pt,
  topsep=${pxToPt(typo.space.bulletsTop)}pt, itemsep=${pxToPt(typo.space.bulletGap)}pt, parsep=0pt,
  align=left, labelwidth=8pt
}

% Skills and languages: one flowing line with grey separators.
\\newcommand{\\cvinlinesep}{{\\color{sepgrey}\\hspace{5pt}\\textbullet\\hspace{5pt}}}
`;
}

function jobTitleSetup(model) {
  const { typo } = model;
  const size = fontSize(typo.jobTitle, 1.2);
  switch (typo.jobTitleStyle) {
    case "semibold-accent":
      return `\\color{accent}\\bfseries${size}`;
    case "semibold":
      return `\\color[HTML]{${hexColor(COLORS.jobTitle)}}\\bfseries${size}`;
    case "italic":
      return `\\color[HTML]{${hexColor(COLORS.jobTitleExecutive)}}\\itshape${size}`;
    default:
      return `\\color[HTML]{${hexColor(COLORS.jobTitle)}}${size}`;
  }
}

// --- Body --------------------------------------------------------------------

function headerBody(model) {
  const { typo, header } = model;
  const centered = typo.headerAlign === "center";
  const lines = [];

  const contact = typo.stackedContact
    ? header.contacts.map(tex).join("\\\\\n")
    : header.contacts.map(tex).join("\\cvsep{}");

  if (centered) lines.push("\\begin{center}");
  lines.push(`\\cvname{${tex(header.name)}}`);
  if (header.jobTitle) {
    lines.push(`\\vspace{${pxToPt(typo.space.jobTitleTop)}pt}`);
    lines.push(`\\cvjobtitle{${tex(header.jobTitle)}}`);
  }
  if (contact) {
    if (typo.space.contactTop) lines.push(`\\vspace{${pxToPt(typo.space.contactTop)}pt}`);
    lines.push(`\\cvcontact{${contact}}`);
  }
  if (centered) lines.push("\\end{center}");

  if (typo.headerRulePx > 0) {
    const color = typo.headerRuleColor === "accent" ? "accent" : "rulegrey";
    lines.push(
      `\\vspace{${pxToPt(typo.space.headerPad)}pt}{\\color{${color}}\\hrule height ${pxToPt(
        typo.headerRulePx
      )}pt}`
    );
  }
  return lines.join("\n");
}

function entryBody(model, item, first) {
  const gap = first
    ? `[${pxToPt(model.typo.space.itemFirstGap)}pt]`
    : "";
  const lines = [`\\cventry${gap}{${tex(item.title)}}{${tex(item.date)}}`];
  if (item.subtitle) lines.push(`\\cvsubtitle{${tex(item.subtitle)}}`);
  if (item.detail) lines.push(`\\cvdetail{${tex(item.detail)}}`);
  if (item.bullets.length) {
    lines.push("\\begin{cvbullets}");
    for (const bullet of item.bullets) lines.push(`  \\item ${tex(bullet)}`);
    lines.push("\\end{cvbullets}");
  }
  return lines.join("\n");
}

function sectionBody(model, block, first) {
  const gap = first ? `[${pxToPt(model.typo.space.sectionFirstGap)}pt]` : "";
  const lines = [`\\cvsection${gap}{${tex(block.title)}}`];
  if (block.kind === "text") {
    const size =
      block.variant === "summary" && model.templateId === "executive"
        ? `{${fontSize(model.typo.summary, 1.55)}${tex(block.text)}\\par}`
        : `{${fontSize(model.typo.summary, model.typo.lineHeight)}${tex(block.text)}\\par}`;
    lines.push(size);
  } else if (block.kind === "inline") {
    lines.push(
      `\\vspace{${pxToPt(model.typo.space.inlineListTop)}pt}{${fontSize(
        model.typo.inlineList,
        model.typo.lineHeight
      )}${block.items.map(tex).join("\\cvinlinesep{}")}\\par}`
    );
  } else {
    block.entries.forEach((item, i) => lines.push(entryBody(model, item, i === 0)));
  }
  return lines.join("\n");
}

// --- Entry point -------------------------------------------------------------

// Builds a complete, compilable .tex document for a CV. Never throws.
export function cvToLatex(cvData, templateId) {
  const model = buildCvModel(cvData, templateId);
  const body = model.sections
    .map((block, i) => sectionBody(model, block, i === 0))
    .join("\n\n");
  const rtlOpen = model.rtl ? "\\begin{arabic}\n" : "";
  const rtlClose = model.rtl ? "\n\\end{arabic}" : "";

  return `${preamble(model)}
\\begin{document}
${rtlOpen}${headerBody(model)}

${body}${rtlClose}
\\end{document}
`;
}
