// ============================================================================
// CV template HTML generator — the single source of truth.
//
// ⚠️ ATS-compatibility note (read before any visual change):
// The output here is the product. It must stay readable by Applicant Tracking
// Systems (ATS) and acceptable to conservative recruiters — locally in
// Palestine and internationally. Every template must keep:
//   - A4 page, single clean column (no complex multi-column layouts that
//     break ATS text extraction).
//   - Neutral text colours + one subtle accent for headings only.
//   - One font family per template (heavier weight for headings is fine).
//   - No icons, no profile photo, no complex tables.
//   - A fixed section order: contact → summary → experience → education →
//     skills → languages → certifications.
//   - Everything in English, left-to-right.
//
// The same output is used for the live preview (inside an iframe) and for the
// PDF generated by Puppeteer (page.setContent), so the PDF matches the preview
// exactly.
// ============================================================================

export const TEMPLATES = [
  {
    id: "classic",
    name: "Classic",
    desc: "Centered name, underlined section titles, comfortable spacing.",
    font: "'Inter', Arial, sans-serif",
    accent: "#0f766e",
  },
  {
    id: "modern",
    name: "Modern",
    desc: "Left-aligned header with uppercase, letter-spaced green headings.",
    font: "'Inter', Arial, sans-serif",
    accent: "#059669",
  },
  {
    id: "professional",
    name: "Professional",
    desc: "Confident header rule and bold green section labels.",
    font: "'Inter', Arial, sans-serif",
    accent: "#047857",
  },
  {
    id: "minimal",
    name: "Minimal",
    desc: "Lots of whitespace, thin rules, understated and clean.",
    font: "'Inter', Arial, sans-serif",
    accent: "#334155",
  },
  {
    id: "elegant",
    name: "Elegant",
    desc: "Classic serif typography with a refined emerald accent.",
    font: "'Lora', Georgia, serif",
    accent: "#065f46",
  },
  {
    id: "compact",
    name: "Compact",
    desc: "Tighter spacing to fit more content on a single page.",
    font: "'Inter', Arial, sans-serif",
    accent: "#15803d",
  },
];

const LABELS = {
  summary: "Professional Summary",
  experience: "Work Experience",
  education: "Education",
  skills: "Skills",
  languages: "Languages",
  certifications: "Certifications",
  present: "Present",
};

function esc(value) {
  if (value === null || value === undefined) return "";
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function fmtRange(start, end, current, presentLabel) {
  const s = esc(start);
  const e = current ? presentLabel : esc(end);
  if (!s && !e) return "";
  if (!s) return e;
  if (!e) return s;
  return `${s} — ${e}`;
}

function getTemplate(templateId) {
  return TEMPLATES.find((t) => t.id === templateId) || TEMPLATES[0];
}

// Builds the CSS for a template. All variants are ATS-safe: one column, one
// accent colour used for headings, the name, and bullet markers only.
function buildStyles(tpl) {
  const base = `
    *{box-sizing:border-box;margin:0;padding:0;}
    html,body{background:#ffffff;}
    body{
      font-family:${tpl.font};
      color:#1a1a1a;
      direction:ltr;
      text-align:left;
      line-height:1.5;
      -webkit-print-color-adjust:exact;
      print-color-adjust:exact;
    }
    .page{
      width:210mm;
      min-height:297mm;
      padding:18mm 16mm;
      margin:0 auto;
      background:#ffffff;
    }
    .name{color:${tpl.accent};}
    a{color:#1a1a1a;text-decoration:none;}
    ul{list-style:none;}
    .section{margin-top:14px;}
    .item{margin-top:10px;}
    .muted{color:#444;}
    .row-between{display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap;}
    .bullets{margin-top:4px;}
    .bullets li{position:relative;padding-left:14px;margin-top:3px;}
    .bullets li::before{
      content:"•";position:absolute;left:0;color:${tpl.accent};
    }
    .contact{margin-top:6px;color:#333;font-size:10.5pt;}
    .contact span{white-space:nowrap;}
    .contact .sep{margin:0 8px;color:#aaa;}
    .skills-list{display:flex;flex-wrap:wrap;gap:6px 10px;margin-top:6px;}
    .skills-list li{
      border:1px solid #ccc;border-radius:4px;padding:2px 8px;font-size:10pt;
    }
    @page{size:A4;margin:0;}
  `;

  const variants = {
    classic: `
      .page{font-size:11pt;}
      .header{text-align:center;border-bottom:2px solid ${tpl.accent};padding-bottom:10px;}
      .name{font-size:24pt;font-weight:800;letter-spacing:0.3px;}
      .job-title{font-size:13pt;color:#333;margin-top:2px;font-weight:600;}
      .contact{text-align:center;}
      .section-title{
        color:${tpl.accent};font-size:13pt;font-weight:800;
        border-bottom:1px solid #d8d8d8;padding-bottom:3px;margin-bottom:2px;
      }
      .item-title{font-weight:700;font-size:11.5pt;}
      .item-sub{font-weight:600;color:#333;}
      .item-date{color:#555;font-size:10pt;}
    `,
    modern: `
      .page{font-size:10.5pt;}
      .header{border-bottom:1px solid #ccc;padding-bottom:12px;}
      .name{font-size:23pt;font-weight:700;}
      .job-title{font-size:12pt;color:#444;margin-top:2px;letter-spacing:1px;}
      .section-title{
        color:${tpl.accent};font-size:11pt;font-weight:700;
        text-transform:uppercase;letter-spacing:2px;margin-bottom:4px;
      }
      .item-title{font-weight:700;font-size:11pt;}
      .item-sub{color:#444;}
      .item-date{color:#666;font-size:9.5pt;}
    `,
    professional: `
      .page{font-size:10.5pt;}
      .header{border-bottom:3px solid ${tpl.accent};padding-bottom:10px;}
      .name{font-size:24pt;font-weight:800;}
      .job-title{font-size:12.5pt;color:${tpl.accent};margin-top:2px;font-weight:700;}
      .section-title{
        color:#ffffff;background:${tpl.accent};font-size:10.5pt;font-weight:700;
        text-transform:uppercase;letter-spacing:1.5px;
        padding:3px 8px;border-radius:3px;margin-bottom:4px;
      }
      .item-title{font-weight:700;font-size:11pt;}
      .item-sub{color:#444;font-weight:600;}
      .item-date{color:#555;font-size:9.5pt;}
    `,
    minimal: `
      .page{font-size:10.5pt;padding:20mm 18mm;}
      .header{padding-bottom:10px;}
      .name{font-size:22pt;font-weight:600;letter-spacing:0.5px;}
      .job-title{font-size:12pt;color:#555;margin-top:2px;font-weight:400;}
      .section{margin-top:18px;}
      .section-title{
        color:${tpl.accent};font-size:10pt;font-weight:600;
        text-transform:uppercase;letter-spacing:3px;
        border-bottom:1px solid #e5e5e5;padding-bottom:4px;margin-bottom:4px;
      }
      .item-title{font-weight:600;font-size:11pt;}
      .item-sub{color:#555;}
      .item-date{color:#777;font-size:9.5pt;}
      .skills-list li{border:none;border-radius:0;padding:0;}
      .skills-list li::after{content:"•";margin-left:10px;color:#bbb;}
      .skills-list li:last-child::after{content:"";}
    `,
    elegant: `
      .page{font-size:11pt;}
      .header{text-align:center;border-bottom:1px solid ${tpl.accent};padding-bottom:12px;}
      .name{font-size:26pt;font-weight:700;letter-spacing:0.5px;}
      .job-title{font-size:12.5pt;color:#555;margin-top:3px;font-style:italic;}
      .contact{text-align:center;}
      .section-title{
        color:${tpl.accent};font-size:13pt;font-weight:700;
        border-bottom:1px solid #ddd;padding-bottom:3px;margin-bottom:3px;
      }
      .item-title{font-weight:700;font-size:11.5pt;}
      .item-sub{color:#444;font-style:italic;}
      .item-date{color:#666;font-size:10pt;}
    `,
    compact: `
      .page{font-size:10pt;padding:14mm 14mm;}
      .section{margin-top:10px;}
      .item{margin-top:7px;}
      .header{border-bottom:1.5px solid ${tpl.accent};padding-bottom:8px;}
      .name{font-size:20pt;font-weight:800;}
      .job-title{font-size:11pt;color:#444;font-weight:600;}
      .section-title{
        color:${tpl.accent};font-size:11pt;font-weight:800;
        text-transform:uppercase;letter-spacing:0.5px;margin-bottom:2px;
      }
      .item-title{font-weight:700;font-size:10.5pt;}
      .item-sub{color:#333;}
      .item-date{color:#555;font-size:9pt;}
      .bullets li{margin-top:1px;}
    `,
  };

  return base + (variants[tpl.id] || variants.classic);
}

function renderContact(p) {
  const parts = [];
  if (p.email) parts.push(`<span>${esc(p.email)}</span>`);
  if (p.phone) parts.push(`<span>${esc(p.phone)}</span>`);
  if (p.location) parts.push(`<span>${esc(p.location)}</span>`);
  if (p.linkedin) parts.push(`<span>${esc(p.linkedin)}</span>`);
  if (p.website) parts.push(`<span>${esc(p.website)}</span>`);
  if (!parts.length) return "";
  return `<div class="contact">${parts.join('<span class="sep">|</span>')}</div>`;
}

function renderSection(title, inner) {
  if (!inner) return "";
  return `<div class="section"><div class="section-title">${esc(title)}</div>${inner}</div>`;
}

// Builds a complete HTML document for a CV.
export function buildCvHtml(cvData, templateId) {
  const data = cvData || {};
  const tpl = getTemplate(templateId);
  const L = LABELS;
  const p = data.personal || {};

  const header = `
    <div class="header">
      <div class="name">${esc(p.fullName) || "Full Name"}</div>
      ${p.jobTitle ? `<div class="job-title">${esc(p.jobTitle)}</div>` : ""}
      ${renderContact(p)}
    </div>`;

  const summary = data.summary
    ? renderSection(L.summary, `<p class="muted">${esc(data.summary)}</p>`)
    : "";

  const experiences = Array.isArray(data.experiences)
    ? data.experiences.filter((e) => e && (e.jobTitle || e.company))
    : [];
  const expInner = experiences
    .map((e) => {
      const bullets = Array.isArray(e.bullets)
        ? e.bullets.filter((b) => b && b.trim())
        : [];
      const bulletsHtml = bullets.length
        ? `<ul class="bullets">${bullets.map((b) => `<li>${esc(b)}</li>`).join("")}</ul>`
        : "";
      const sub = [e.company, e.location].filter(Boolean).map(esc).join(" — ");
      return `
        <div class="item">
          <div class="row-between">
            <span class="item-title">${esc(e.jobTitle)}</span>
            <span class="item-date">${fmtRange(e.startDate, e.endDate, e.current, L.present)}</span>
          </div>
          ${sub ? `<div class="item-sub">${sub}</div>` : ""}
          ${bulletsHtml}
        </div>`;
    })
    .join("");
  const experienceSection = expInner ? renderSection(L.experience, expInner) : "";

  const education = Array.isArray(data.education)
    ? data.education.filter((e) => e && (e.degree || e.institution))
    : [];
  const eduInner = education
    .map((e) => {
      const sub = [e.institution, e.location].filter(Boolean).map(esc).join(" — ");
      return `
        <div class="item">
          <div class="row-between">
            <span class="item-title">${esc(e.degree)}</span>
            <span class="item-date">${fmtRange(e.startDate, e.endDate, false, L.present)}</span>
          </div>
          ${sub ? `<div class="item-sub">${sub}</div>` : ""}
          ${e.details ? `<div class="muted">${esc(e.details)}</div>` : ""}
        </div>`;
    })
    .join("");
  const educationSection = eduInner ? renderSection(L.education, eduInner) : "";

  const skills = Array.isArray(data.skills)
    ? data.skills.filter((s) => s && s.trim())
    : [];
  const skillsSection = skills.length
    ? renderSection(
        L.skills,
        `<ul class="skills-list">${skills.map((s) => `<li>${esc(s)}</li>`).join("")}</ul>`
      )
    : "";

  const languages = Array.isArray(data.languages)
    ? data.languages.filter((l) => l && l.name)
    : [];
  const langSection = languages.length
    ? renderSection(
        L.languages,
        `<ul class="skills-list">${languages
          .map((l) => `<li>${esc(l.name)}${l.level ? ` — ${esc(l.level)}` : ""}</li>`)
          .join("")}</ul>`
      )
    : "";

  const certs = Array.isArray(data.certifications)
    ? data.certifications.filter((c) => c && c.name)
    : [];
  const certInner = certs
    .map(
      (c) => `
        <div class="item">
          <div class="row-between">
            <span class="item-title">${esc(c.name)}</span>
            <span class="item-date">${esc(c.date)}</span>
          </div>
          ${c.issuer ? `<div class="item-sub">${esc(c.issuer)}</div>` : ""}
        </div>`
    )
    .join("");
  const certSection = certInner ? renderSection(L.certifications, certInner) : "";

  const styles = buildStyles(tpl);

  return `<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>CV</title>
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,400&display=swap" rel="stylesheet" />
<style>${styles}</style>
</head>
<body>
  <div class="page">
    ${header}
    ${summary}
    ${experienceSection}
    ${educationSection}
    ${skillsSection}
    ${langSection}
    ${certSection}
  </div>
</body>
</html>`;
}
